language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby

before_install:
  - sudo apt-get update
  - sudo apt-get install -y advancecomp gifsicle jpegoptim libjpeg-progs optipng pngcrush
  - sudo apt-get install jruby-openssl
